spring.application.name=starfleet-api

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:starfleet
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.api-key=starfleet-secret-key